### ISSUE TITLE
vectorization in stri_sub

### ISSUE THREAD

**Issue by markdanese** [Rexamine/stringi#167] opened 2015-06-14 20:45 UTC
Right now the help file says that it is "Vectorized over str, [value], from and (to or length)."  But in reality it seems that it is only vectorized over **one** of these.  And it seems that the default it to vectorize over str if both are present.  Perhaps the documentation could be made a bit more clear?

background and comments:
I was trying to process a bunch of lines from a fixed width text file and parse them into columns using a matrix of from and to values.  But it seems that I can read in all the lines and take one substring from each, or I can read in one line at a time and take all 100 substrings.  But I can't read in each line **and** take a substring of each line.

It seems that, for this function, it might be nice to handle nested loops.  More broadly, I could see having a "stri_nested_loop" function where stringi reads in lines and then calls a second stri function.  For example, the new stri_read_lines might benefit from allowing for another string parsing function after each line is read.

I do realize that lapply does this, and that worked.  And the readr package read_fwf also works nicely.  By the way, stri_read_lines also worked nicely on a 700,000 line, 300 characters per line, fixed width file.  It was about the same speed as fread in the data.table package, which is about as fast as one can go.

**Comment by gagolews** [comment] 2015-06-15 07:35
Thanks for the report on `stri_read_lines`. :)
Is this feature request related to #30?
If not, then I might be missing something: in such a case, could you prepare an example (input, proposed functions' call scheme, desired output) so that I get a better insight to your suggestion? Thanks

**Comment by markdanese** [comment] 2015-06-15 16:45
Maybe it is.  I couldn't decipher all that was going on when I saw that, but I am still pretty new to string manipulation.  Below is my example, but feel free to close this if it is the same.

```
# toy data and split matrix
x <- c("abcdefgh", "ijklmnop")
split <- matrix(1:8, ncol = 2, byrow = TRUE)
```  

`stri_sub(x, split)`
gives: 
`[1] "ab" "kl" "ef" "op"`  

but I was hoping for this:
```
[[1]]
[1] "ab" "cd" "ef" "gh"
[[2]]
[1] "ij" "kl" "mn" "op"
```

or even better, this:
```
     [,1] [,2] [,3] [,4]
[1,] "ab" "cd" "ef" "gh"
[2,] "ij" "kl" "mn" "op"
```

The last piece is accomplished by `do.call(rbind, lapply(x, stri_sub, split))` but I was hoping it might be faster if it were all done in c++.

**Comment by gagolews** [comment] 2015-06-16 11:12
Yep, it's a duplicate of #30. Scheduled for stringi_0.6

**Closed by gagolews** 2015-06-16 11:12 UTC

**Comment by gagolews** [comment] 2019-02-23 12:13
Finally I've had time for this. There's a new function, `stri_sub_all` now

```
> x <- c("abcdefgh", "ijklmnop")
> split <- matrix(1:8, ncol = 2, byrow = TRUE)
> split
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
> stri_sub_all(x, split)
[[1]]
[1] "ab" "cd" "ef" "gh"

[[2]]
[1] "ij" "kl" "mn" "op"
> stri_list2matrix(stri_sub_all(x, split), byrow=TRUE)
     [,1] [,2] [,3] [,4]
[1,] "ab" "cd" "ef" "gh"
[2,] "ij" "kl" "mn" "op"
```
