### ISSUE TITLE
Locate groups?

### ISSUE THREAD

**Issue by hadley** [Rexamine/stringi#195] opened 2015-10-21 13:28 UTC
Is there an existing function to find the location of not just the complete match, but the groups within the match? i.e `stri_locate()` is to `stri_extract()` as ??? is to `stri_match()`?

I'd like this because I'm thinking about making an html widget that displays matches - I thought it might be helpful when learning and debugging regular expressions.

**Comment by gagolews** [comment] 2015-10-21 14:47
I also find that useful. Duplicate of #25. I'll have time to work on that in >= November (finally!).

**Closed by gagolews** 2015-10-21 14:47 UTC
